//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5TN230
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_giong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ca_giong()
        {
            this.chi_tiet_don_dat = new HashSet<chi_tiet_don_dat>();
            this.hinh_anh = new HashSet<hinh_anh>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> NgayTuoi { get; set; }
        public Nullable<int> loai_ca_giong_Ma { get; set; }
    
        public virtual loai_ca_giong loai_ca_giong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_dat> chi_tiet_don_dat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hinh_anh> hinh_anh { get; set; }
    }
}
