//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5TN230
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_don_dat
    {
        public int ca_giong_Ma { get; set; }
        public int don_dat_Ma { get; set; }
        public Nullable<int> SoLuongDat { get; set; }
        public Nullable<long> DonGia { get; set; }
    
        public virtual ca_giong ca_giong { get; set; }
        public virtual don_dat don_dat { get; set; }
    }
}
