//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5TN230
{
    using System;
    using System.Collections.Generic;
    
    public partial class don_dat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public don_dat()
        {
            this.chi_tiet_don_dat = new HashSet<chi_tiet_don_dat>();
            this.hoa_don = new HashSet<hoa_don>();
        }
    
        public int Ma { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
        public Nullable<long> TongTien { get; set; }
        public Nullable<int> khach_hang_Ma { get; set; }
        public string nhan_vien_Ma { get; set; }
        public Nullable<int> trang_thai_Ma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_dat> chi_tiet_don_dat { get; set; }
        public virtual khach_hang khach_hang { get; set; }
        public virtual nhan_vien nhan_vien { get; set; }
        public virtual trang_thai trang_thai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoa_don> hoa_don { get; set; }
    }
}
