//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5TN230
{
    using System;
    using System.Collections.Generic;
    
    public partial class hinh_anh
    {
        public int Ma { get; set; }
        public string Ten { get; set; }
        public Nullable<int> ca_giong_Ma { get; set; }
    
        public virtual ca_giong ca_giong { get; set; }
    }
}
