//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5TN230
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoa_don
    {
        public int Ma { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> don_dat_Ma { get; set; }
    
        public virtual don_dat don_dat { get; set; }
    }
}
