//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5TN230
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FishMarketEntities : DbContext
    {
        public FishMarketEntities()
            : base("name=FishMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ca_giong> ca_giong { get; set; }
        public virtual DbSet<chi_tiet_don_dat> chi_tiet_don_dat { get; set; }
        public virtual DbSet<don_dat> don_dat { get; set; }
        public virtual DbSet<hinh_anh> hinh_anh { get; set; }
        public virtual DbSet<hoa_don> hoa_don { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<loai_ca_giong> loai_ca_giong { get; set; }
        public virtual DbSet<nhan_vien> nhan_vien { get; set; }
        public virtual DbSet<quyen> quyens { get; set; }
        public virtual DbSet<trang_thai> trang_thai { get; set; }
    }
}
