//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5TN230
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class nhan_vien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhan_vien()
        {
            this.don_dat = new HashSet<don_dat>();
        }

        [Required(ErrorMessage = "Mã nhân viên không để trống!")]
        [RegularExpression("^[0-9]{4,20}$", ErrorMessage = "Vui lòng nhập đúng 4-20 số cho nhân viên!")]
        public string Ma { get; set; }
        [Required(ErrorMessage = "Tên nhân viên không để trống!")]
        public string Ten { get; set; }
        [Required(ErrorMessage = "SĐT không để trống!")]
        //[RegularExpression(" /(84|0[3|5|7|8|9])+([0 - 9]{8})\b/", ErrorMessage = "Vui lòng nhập số điện thoại Việt Nam")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Mật khẩu không để trống!")]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "Địa chỉ nhân viên không để trống!")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Quyền nhân viên không để trống!")]
        public int quyen_Ma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<don_dat> don_dat { get; set; }
        public virtual quyen quyen { get; set; }
    }
}
